# Wire up travis
language: python
sudo: false

matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.6
          env: TOXENV=flake8
        - python: 3.6
          env: TOXENV=coverage

install:
  - travis_retry pip install pipenv
  - travis_retry pipenv install --dev

script:
  - travis_retry tox
