# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
