# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20180514_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataWithoutName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='')),
            ],
        ),
    ]
