# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_datawithoutname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatetimeFilterTestingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
